### ISSUE TITLE
Game Engine - showdown()

### ISSUE THREAD

**Issue by furuutsuponchisamurai** [furuutsuponchisamurai/poker_project#2]
Today's players are: 0,1
0
Check, Fold, or Raise?check
1
Check, Fold, or Raise?check
9 of Hearts
2 of Spades
Ace of Spades
0
Check, Fold, or Raise?raise
Choose a number between 0 and 50000500
1
Call, Fold, or Raise?call
9 of Hearts
2 of Spades
Ace of Spades
3 of Hearts
0
Check, Fold, or Raise?check
1
Check, Fold, or Raise?fold
9 of Hearts
2 of Spades
Ace of Spades
3 of Hearts
8 of Diamonds
Traceback (most recent call last):
  File "/Users/AK47/PycharmProjects/poker_project/run.py", line 7, in <module>
    game.round()
  File "/Users/AK47/PycharmProjects/poker_project/poker_cards/game_engine.py", line 237, in round
    self.showdown()
  File "/Users/AK47/PycharmProjects/poker_project/poker_cards/game_engine.py", line 142, in showdown
    min_value = min(eval_dict.values())
ValueError: min() arg is an empty sequence

**Comment by furuutsuponchisamurai** [comment]
It seems this is happening because there aren't enough cards to evaluate.
